name: Clone repository

on: 
# Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  clone:
    name: Clone
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH
      uses: appleboy/ssh-action@master
      with:
        host: ec2-3-127-149-11.eu-central-1.compute.amazonaws.com
        username: ubuntu
        password: ${{ secrets.RISE_SECRET }}
        port: 22
        script: cd /var/www/html && sudo mkdir testFolder
   
