name: Clone repository

on: 
# Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  clone:
    name: Clone
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH
      uses: appleboy/ssh-action@master
      with:
        host: ec2-13-58-176-94.us-east-2.compute.amazonaws.com
        username: ubuntu
        key: ${{ secrets.RISE_SECRET }}
        password: rise@2020
        port: 22
        script: cd /var/www/html && sudo mkdir testFolder
   
